# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 1.8
          - 1.11
          - 1.17
          - 19.0.2+7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Verify formatting
        run: ./gradlew spotlessCheck
      - name: Create bundle
        run: ./gradlew shadowDistZip
      - name: Run automated tests
        run: ./gradlew test
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: Briss-2.0-${{ matrix.java-version }}
          path: build/distributions/*.zip
